### ISSUE TITLE
Problem with MER

### ISSUE THREAD

**Issue by Kehindeajayi01** [CederGroupHub/text-mined-synthesis#5]
When I try to import MatRecognition from material_entity_recognition, I get the error "zsh: illegal hardware instruction python3"

I have installed the git LFS successfully and installed all the dependencies as described in the README file.

Please can anyone help out.

Thanks

**Comment by zhugeyicixin** [comment]
> When I try to import MatRecognition from material_entity_recognition, I get the error "zsh: illegal hardware instruction python3"
> 
> I have installed the git LFS successfully and installed all the dependencies as described in the README file.
> 
> Please can anyone help out.
> 
> Thanks

Hi! Glad to help you with that! May I ask what is your python version? I just reinstall everything and it seemed to be OK. Could you try to install from https://github.com/CederGroupHub/MatEntityRecognition so that we'll be aligned? I also replace the Folder MatEntityRecognition with a submodule link just now.

**Comment by christina0106** [comment]
Hi, 

The materials-entity-recognition-3.2 have been installed successfully ,
in windows _X86, python3.8 version

The error happend on the model exacuted processing shown as follows:

Input:
model = MatRecognition()

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\mat_models.py", line 642, in __init__
    self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path)
  File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\model_framework.py", line 941, in reload_model
    model = NERModel.create_scratch_model(
  File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\model_framework.py", line 891, in create_scratch_model
    model_config = pickle.load(fr)
_pickle.UnpicklingError: invalid load key, 'v'.

It was a great pleasure to get a reply.

**Comment by zhugeyicixin** [comment]
This issue likely stems from a version compatibility problem among different packages. I've updated the setup.py file, which should resolve the issue. If the problem persists, consider installing a specific version of transformers using the following command: pip install transformers==4.11.3. I have tested versions from 4.11.3 to 4.34.0 of transformers, and all have worked as expected.

**Comment by zhugeyicixin** [comment]
> Hi,
> 
> The materials-entity-recognition-3.2 have been installed successfully , in windows _X86, python3.8 version
> 
> The error happend on the model exacuted processing shown as follows:
> 
> Input: model = MatRecognition()
> 
> Error: Traceback (most recent call last): File "", line 1, in File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\mat_models.py", line 642, in **init** self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path) File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\model_framework.py", line 941, in reload_model model = NERModel.create_scratch_model( File "C:\Users\99239\Downloads\MatEntityRecognition\materials_entity_recognition\scripts\model_framework.py", line 891, in create_scratch_model model_config = pickle.load(fr) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> It was a great pleasure to get a reply.

This issue likely stems from a version compatibility problem among different packages. I've updated the setup.py file, which should resolve the issue. If the problem persists, consider installing a specific version of transformers using the following command: pip install transformers==4.11.3. I have tested versions from 4.11.3 to 4.34.0 of transformers, and all have worked as expected.
