### ISSUE TITLE
Problem with MER

### ISSUE THREAD

**Issue by mostly-harmless-earth** [CederGroupHub/text-mined-synthesis#6]
this is to sincerely seek your professional acvice about the MER.
Following the steps in the README, i try to run the example in the test folder, and encounter with this error:
 File "D:\aconcon\envs\txmine\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1151, in weight_decay_fn
      wd = tf.cast(self.weight_decay, variable.dtype)
Node: 'Cast_1'
Cast string to float is not supported
         [[{{node Cast_1}}]] [Op:__inference_train_function_52474]

**Comment by zhugeyicixin** [comment]
This issue likely stems from a version compatibility problem among different packages. I've updated the setup.py file, which should resolve the issue. If the problem persists, consider installing a specific version of transformers using the following command: pip install transformers==4.11.3. I have tested versions from 4.11.3 to 4.34.0 of transformers, and all have worked as expected.
